[project]
name = "mergenetic"
version = "0.1.0"
description = "Evolutionary model merging for LLMs"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "Tommaso Mencattini", email = "tommaso.mencattini@epfl.ch" }]
keywords = ["llm", "model merging", "evolutionary optimization", "mergekit"]
requires-python = ">=3.11,<3.12"

dependencies = [
  "about-time==4.2.1",
  "accelerate==1.3.0",
  "aiohappyeyeballs==2.3.4",
  "aiohttp==3.10.0",
  "aiosignal==1.3.1",
  "alive-progress==3.1.5",
  "annotated-types==0.7.0",
  "attrs==23.2.0",
  "autograd==1.7.0",
  "bitsandbytes==0.45.4",
  "certifi==2024.7.4",
  "charset-normalizer==3.3.2",
  "click==8.1.8",
  "cma==3.2.2",
  "contourpy==1.3.0",
  "cycler==0.12.1",
  "datasets==2.20.0",
  "deprecated==1.2.14",
  "dill==0.3.8",
  "e==1.4.5",
  "einops==0.7.0",
  "fasttext==0.9.3",
  "filelock==3.15.4",
  "fonttools==4.53.1",
  "frozenlist==1.4.1",
  "fsspec==2024.5.0",
  "git-python==1.0.3",
  "gitdb==4.0.11",
  "gitpython==3.1.43",
  "grapheme==0.6.0",
  "huggingface-hub==0.24.5",
  "idna==3.7",
  "immutables==0.21",
  "jinja2==3.1.4",
  "joblib==1.4.2",
  "kiwisolver==1.4.5",
  "markupsafe==2.1.5",
  "matplotlib==3.9.2",
  "mergekit @ git+https://github.com/arcee-ai/mergekit",
  "mpmath==1.3.0",
  "multidict==6.0.5",
  "multiprocess==0.70.16",
  "networkx==3.3",
  "numpy==2.0.1",
  "nvidia-cublas-cu12==12.1.3.1",
  "nvidia-cuda-cupti-cu12==12.1.105",
  "nvidia-cuda-nvrtc-cu12==12.1.105",
  "nvidia-cuda-runtime-cu12==12.1.105",
  "nvidia-cudnn-cu12==9.1.0.70",
  "nvidia-cufft-cu12==11.0.2.54",
  "nvidia-curand-cu12==10.3.2.106",
  "nvidia-cusolver-cu12==11.4.5.107",
  "nvidia-cusparse-cu12==12.1.0.106",
  "nvidia-nccl-cu12==2.20.5",
  "nvidia-nvjitlink-cu12==12.6.20",
  "nvidia-nvtx-cu12==12.1.105",
  "packaging==24.1",
  "pandas==2.2.2",
  "peft==0.12.0",
  "pillow==10.4.0",
  "plotly==5.23.0",
  "protobuf==5.27.3",
  "psutil==6.0.0",
  "pyarrow",
  "pyarrow-hotfix==0.6",
  "pybind11==2.13.1",
  "pydantic==2.10.6",
  "pydantic-core==2.27.2",
  "pymoo==0.6.1.3",
  "pyparsing==3.1.4",
  "python-dateutil==2.9.0.post0",
  "pytz==2024.1",
  "pyyaml==6.0.1",
  "regex==2024.7.24",
  "requests==2.32.3",
  "safetensors==0.5.2",
  "scikit-learn==1.5.1",
  "scipy==1.14.0",
  "sentencepiece==0.2.0",
  "six==1.16.0",
  "smmap==5.0.1",
  "sympy==1.13.1",
  "tenacity==9.0.0",
  "threadpoolctl==3.5.0",
  "tokenizers==0.20.1",
  "torch==2.4.0",
  "tqdm==4.67.1",
  "transformers==4.45.2",
  "triton==3.0.0",
  "typing-extensions==4.12.2",
  "tzdata==2024.1",
  "urllib3==2.2.2",
  "wheel==0.41.2",
  "wrapt==1.16.0",
  "xxhash==3.4.1",
  "yarl==1.9.4",
  "lm_eval @ git+https://github.com/EleutherAI/lm-evaluation-harness.git",
  "rich",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
