base_model: OpenLLM-Ro/RoMistral-7b-Instruct
dtype: bfloat16
merge_method: slerp
parameters:
  t:
  - filter: self_attn
    value:
    - 0.3
    - 0.7
    - 0.5
    - 0.9
    - 0.8
  - filter: mlp
    value:
    - 0.1
    - 0.1
    - 0.3
    - 0.8
    - 1.0
  - value: 0.6
slices:
- sources:
  - layer_range:
    - 0
    - 32
    model: OpenLLM-Ro/RoMistral-7b-Instruct
  - layer_range:
    - 0
    - 32
    model: meta-math/MetaMath-Mistral-7B
